// AUTO-GENERATED by scripts/gen-font-atlas.mjs — DO NOT EDIT
// Glyph order of every packed atlas in font-atlas.ts: ASCII printable, Latin-1
// (U+00A0–U+00FF), then U+2026 (…).

/** Index of a codepoint in every packed atlas, or -1 if not covered. */
export function fontGlyphIndex(codepoint: number): number {
  if (codepoint >= 32 && codepoint <= 126) return codepoint - 32;
  if (codepoint >= 0xa0 && codepoint <= 0xff) return codepoint - 0xa0 + 95;
  return codepoint === 0x2026 ? 191 : -1;
}
