// AUTO-RUN: node ts/scripts/gen-splash.mjs (from deckbridge/)
// Regenerates ts/src/assets/splash-states.ts — commit the output.
import { createCanvas } from '@napi-rs/canvas';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const assetDir = join(__dir, '../src/assets');

const W = 112, H = 112;
const WHITE = '#ffffff';
const BG = {
  connecting: '#cc8800',
  connected: '#1a8c1a',
  error: '#b00020',
};

function makeCheckmark(ctx, scale = 1) {
  ctx.strokeStyle = WHITE;
  ctx.lineWidth = 10 * scale;
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  ctx.beginPath();
  ctx.moveTo(20 * scale, 62 * scale);
  ctx.lineTo(44 * scale, 86 * scale);
  ctx.lineTo(92 * scale, 24 * scale);
  ctx.stroke();
}

function makeCross(ctx) {
  ctx.strokeStyle = WHITE;
  ctx.lineWidth = 10;
  ctx.lineCap = 'round';
  ctx.beginPath();
  ctx.moveTo(38, 18);
  ctx.lineTo(74, 54);
  ctx.moveTo(74, 18);
  ctx.lineTo(38, 54);
  ctx.stroke();
}

function makeDot(ctx) {
  ctx.fillStyle = WHITE;
  ctx.beginPath();
  ctx.arc(W / 2, 32, 8, 0, Math.PI * 2);
  ctx.fill();
}

function newCanvas(bg) {
  const c = createCanvas(W, H);
  const ctx = c.getContext('2d');
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);
  ctx.fillStyle = WHITE;
  ctx.textAlign = 'center';
  return { c, ctx };
}

function makeConnecting() {
  const { c, ctx } = newCanvas(BG.connecting);
  makeDot(ctx);
  ctx.font = 'bold 18px sans-serif';
  ctx.fillText('connecting', W / 2, 70);
  return c.toBuffer('image/jpeg', 90);
}

function makeConnected() {
  const { c, ctx } = newCanvas(BG.connected);
  ctx.save();
  ctx.translate(0, -16);
  makeCheckmark(ctx, 0.7);
  ctx.restore();
  ctx.font = 'bold 18px sans-serif';
  ctx.fillText('connected', W / 2, 90);
  return c.toBuffer('image/jpeg', 90);
}

function makeError() {
  const { c, ctx } = newCanvas(BG.error);
  makeCross(ctx);
  ctx.font = 'bold 18px sans-serif';
  ctx.fillText('error', W / 2, 90);
  return c.toBuffer('image/jpeg', 90);
}

// Best-effort: strip APP2 (0xFFE2) ICC-profile segment(s) that @napi-rs/canvas
// embeds. Walk markers from offset 2; for each 0xFFEn marker read the 2-byte
// big-endian length and splice the whole segment out if it is APP2.
function stripIccApp2(buf) {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return buf;
  const out = [buf.subarray(0, 2)];
  let i = 2;
  while (i + 4 <= buf.length && buf[i] === 0xff) {
    const marker = buf[i + 1];
    // APPn markers are 0xE0..0xEF and carry a 2-byte length.
    if (marker >= 0xe0 && marker <= 0xef) {
      const len = (buf[i + 2] << 8) | buf[i + 3];
      const segEnd = i + 2 + len;
      if (segEnd > buf.length) break; // malformed; bail, keep original tail
      if (marker !== 0xe2) out.push(buf.subarray(i, segEnd));
      i = segEnd;
    } else {
      break; // reached SOF/other; copy the rest verbatim (entropy data follows)
    }
  }
  out.push(buf.subarray(i));
  return Buffer.concat(out);
}

mkdirSync(assetDir, { recursive: true });

const states = {
  connecting: stripIccApp2(makeConnecting()),
  connected: stripIccApp2(makeConnected()),
  error: stripIccApp2(makeError()),
};

for (const [name, buf] of Object.entries(states)) {
  const ok = buf[0] === 0xff && buf[1] === 0xd8
    && buf[buf.length - 2] === 0xff && buf[buf.length - 1] === 0xd9;
  if (!ok) throw new Error(`${name}: not a valid JPEG (SOI/EOI check failed)`);
}

const entries = Object.entries(states)
  .map(([name, buf]) => `  ${name}: '${buf.toString('base64')}',`)
  .join('\n');

writeFileSync(
  join(assetDir, 'splash-states.ts'),
  `// AUTO-GENERATED by scripts/gen-splash.mjs — DO NOT EDIT\n` +
  `export const SPLASH_STATES: Record<'connecting' | 'connected' | 'error', string> = {\n` +
  entries + '\n};\n',
);

for (const [name, buf] of Object.entries(states)) {
  console.log(`${name}: ${buf.length}B`);
}
