// Wire DTOs live in the `web-contract` leaf (../contract.ts) — the one element
// web-client may import besides itself, type-only. Re-exported here under the
// names the client already uses, so call sites keep importing from ui-types.
export type {
  ClientApp,
  CommEntry as CommLog,
  DeviceOverridesView,
  DockStatus as DockUi,
  EncoderCommands,
  EncoderSettings,
  ExtraKeyConfig as ExtraKeyCfg,
  ExtraKeyPreview,
  ExtraKeyPreviewResponse,
  ExtraKeyPressAction,
  ExtraKeyTextSize,
  ExtraKeyTextStyle,
  ExtraKeyWidget,
  ExtraKeyWrap,
  LogEntry as ServerLog,
  MockDeviceConfig as MockConfig,
  PluginStatus,
  PluginsInfo,
  StateResponse,
  Stats,
  StatusSnapshot as Status,
  StripWriteMsg,
  DeviceIdentity,
  RealDeviceIdentity,
  KeyEventEntry as KeyEvent,
  DeviceModelInfo as DeviceModel,
  TouchImageMsg,
  TouchStripMode,
  TouchStripSize,
  TuningCropRect as DeviceCropRect,
  TuningImage as DeviceImageOverride,
  UpdateInfo,
  WidgetDisplayInfo,
  WsEvents,
} from '../contract.js';
